// src/front-end/react/containers/app-react.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { changeScreen } from '../../actions/app.actions';
import { Button } from '../components';
import { Config } from './config';
import { partial } from '../../../util';
import {windowApp, verticalUiClass} from '../../styles';

import {
  Game,
} from './game';

function mapStateToProps(state) {
  return {
    currentScreen: state.app.currentScreen,
    screens: state.app.screens,
  };
}

function mapDispatchToProps(dispatch)  {
  return {
    changeScreen: (id) => dispatch(changeScreen(id)),
  };
}

export const App = connect(
  mapStateToProps,
  mapDispatchToProps
)(React.createClass({
  render() {
    return (<div>
      <div className={ verticalUiClass }>
      {
        this.props.screens.map((screen, i) => {
          if (this.props.currentScreen === screen.id) {
            return null;
          }
          return (<Button key = {i}
                          value={ screen.name }
                          onClick={
                            partial(this.props.changeScreen, screen.id)
                          }/>);
        })
      }
      </div>
      {
        (() => {
          switch (this.props.currentScreen) {
            case 'config':
              return (<Config />);
            case 'game':
              return (<Game />);
          }
        })()
      }
    </div>);
  },
}));

// src/front-end/angular/containers/app-angular.ts
import { Component } from '@angular/core';
import { NgRedux, select } from 'ng2-redux';
import { store } from '../../store/store';
import { IState } from '../../reducers/root.reducer';
import { Game } from './game.container';
import { Observable } from 'rxjs/Rx';
import { changeScreen } from '../../actions/app.actions';
import { GameConfig } from './config.container';
import { Button, } from '../components';
import {
  flex,
  flexCol,
  flex11auto,
  windowApp,
  windowApplet,
} from '../../styles';

const angularApplet = `${flex} ${flexCol} ${flex11auto}`;

@Component({
  directives: [
    Button,
    Game,
    GameConfig,
  ],
  selector: 'bd-angular',
  template: `
    <button *ngFor="let screen of (screens$ | async)"
       [onClick]="changeScreen(screen.id)"
       [value]="screen.name"></button>
    <div class="${angularApplet}" [ngSwitch]="(currentScreen$ | async)">
      <bd-game class="${windowApplet}" *ngSwitchCase="'game'"></bd-game>
      <bd-config class="${windowApplet}" *ngSwitchCase="'config'"></bd-config>
    </div>
`,
})
export class App {
  @select(
    (state) => state.app.currentScreen) currentScreen$: Observable<number>;
  @select((state) => state.app.screens
    .filter((screen) => screen.id !== state.app.currentScreen )) screens$;

  constructor(private ngRedux: NgRedux<IState>) {
    this.ngRedux.provideStore(store);
  }

  changeScreen(screen: string) {
    return () => this.ngRedux.dispatch(changeScreen(screen));
  }
}
