// src/front-end/react/components/forms/number.tsx
import * as React from 'react';
import { clamp, numberFromString } from '../../../../util';

export function Number({ value, onChange, min, max }) {
  if (min === undefined) {
    min = NaN;
  }
  if (max === undefined) {
    max = NaN;
  }
  return (
    <input type='text'
           onChange={ (e) => onChange(
             clamp(
               numberFromString(e.target.value),
               min, max)) }
           value={ value } />
      );
}

// src/front-end/angular/components/forms/number.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
} from '@angular/core';

import {
  clamp,
  numberFromString,
} from '../../../../util';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'bd-number',
  template: `
    <input 
      type='string' 
      [ngModel]="model" 
      (change)="onChange($event)">
`,
})
export class Number {
  @Input() model: number;
  @Input() min: number = NaN;
  @Input() max: number = NaN;
  @Output() update: EventEmitter<number> = new EventEmitter<number>();

  onChange($event) {
    let val = numberFromString($event.target.value);

    this.model = clamp(val, this.min, this.max);
    this.update.emit(val);
  }
}
