// src/front-end/react/components/forms/select.tsx
import * as React from 'react';

export function Select({ byValue, selected, options, onChange }) {
  if (byValue) {
    return (<select value={ selected }
                  onChange={ (e) => onChange(e.target.value) }>{
    options.map((opt, i) => <option key={i} value={opt}>{ opt }</option>)
  }</select>);
  }
  return (<select value={ selected }
                  onChange={ (e) => onChange(e.target.value) }>{
    options.map((opt, i) => <option key={i} value={i}>{ opt }</option>)
  }</select>);
}

// src/front-end/angular/components/forms/select.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
} from '@angular/core';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'bd-select',
  template: `
    <select [ngModel]="model" 
    (change)="update.emit({ 
    index: $event.target.value, 
    value: byValue ? $event.target.value : options[$event.target.value]
    })">
      <option 
        *ngFor="let selected of options; let i = index" 
        [value]="byValue ? selected : i">
          {{ selected }}
      </option> 
    </select>

`,
})
export class Select {
  @Input() model: number;
  @Input() options: string[];
  @Input() byValue: boolean = false;
  @Output() update: EventEmitter<{ index: number, value: string}> =
    new EventEmitter<{ index: number, value: string}>();
}
