// src/front-end/react/components/forms/string.tsx
import * as React from 'react';
import { identity } from '../../../../util';

export function String({ value, onChange, sanitize }) {
  if (sanitize === undefined) {
    sanitize = identity;
  }
  return (
    <input type='text'
           onChange={ (e) => onChange(sanitize(e.target.value)) }
           value={ value } />
  );
}

// src/front-end/angular/components/forms/string.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
} from '@angular/core';

import {
  identity,
} from '../../../../util';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'bd-string',
  template: `
    <input 
      type='string' 
      [ngModel]="model" 
      (change)="onChange($event)">
`,
})
export class String {
  @Input() model: string;
  @Input() sanitizer: (val: string) => string = identity;
  @Output() update = new EventEmitter<string>();

  onChange($event) {
    this.update.emit(
      this.sanitizer($event.target.value)
    );
  }
}
