// src/front-end/react/components/block.tsx
import * as React from 'react';
import { columnsFromBlock } from '../../../engine/block';

const boxStyle = 'bd-border bd-border-white bd-margin-bottom bd-margin-left';

export function Block(props) {
  const cols = columnsFromBlock(props.block);

  return (<div className={ boxStyle }>
    <table>
      <caption>{ props.block.name }</caption>
      <tbody>
      {
        cols.map((row, i) => (<tr key={i}>
          { row.map((el, j) => (<td key={j} className={
            el ? 'bd-border bd-border-white' : '' 
          }>{el || ''}</td>)) } 
        </tr>))
      }
      </tbody>
    </table>
  </div>);
}

// src/front-end/angular/components/block.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
} from '@angular/core';

import { boxStyle } from '../../styles';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'block',
  template: `
    <div class="${boxStyle}">
      <table>
        <caption>{{ name }}</caption>
        <tbody>
          <tr *ngFor="let col of cols">
            <td *ngFor="let el of col"
              [ngClass]="el ? 'bd-border bd-border-white' : ''">
              {{ el || '' }}
            </td> 
          </tr>
        </tbody>
      </table>
    </div>
`,
})
export class Block {
  @Input() cols: number[][];
  @Input() name: string;
}
