// src/front-end/react/components/board.tsx
import * as React from 'react';
import { Tile } from './';
import {
  board,
  flexGrowRow,
} from '../../styles';

export function Board(props) {
  const jsx = boardToJsx(props.board, props.width);
  return (
    <div className="ba bw2 b--react-blue mr4 shadow-react-blue">
      <h3 className="black bg-react-blue f3 mb0 mt0 tc">LEVEL {props.level}</h3>
      <div style={ props.styles } className={ board }>
        {
          jsx.map((el, i) => (
          <div key={i} className={ flexGrowRow }>{ el }</div>))
        }
      </div>
    </div>
    );
}

function boardToJsx(board: number[], width): number[][] {
  const cols = [];
  let row;
  board.forEach((el, i) => {
    if (i % width === 0) {
      row = [];
    }
    row.push(<Tile key={i} value={el}></Tile>);
    if (row.length === width) {
      cols.push(row);
    }
  });
  return cols;
}

// src/front-end/angular/components/board.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { board, emptyTile, flexGrowRow, tileByNumber } from '../../styles';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'board',
  host: {
    class:
      'ba bw2 b--angular-red mr2 mr4-ns flex flex-column shadow-angular-red w-two-thirds',
  },
  template: `
    <h3 class="blue-black bg-angular-red f4 f2-m f1-l ma0 pt1 pt2-m pt3-l tc">LEVEL {{level}}</h3>
    <div class="${board}">
      <div class="${flexGrowRow}" *ngFor="let row of board; trackBy: trackCol">
        <tile [ngClass]="tile === 0 ? emptyTile : tileByNumber(tile)"
          *ngFor="let tile of row; trackBy: trackRow" [value]="tile"></tile>
      </div>
    </div>
`,
})
export class Board {
  @Input() board: number[][];
  @Input() level: number;
  @Input() width: number;
  @Input() isPaused: boolean;

  cols: number[][];
  emptyTile: string = emptyTile;
  rows: number[];
  tileByNumber = tileByNumber;

  trackCol(index: number) {
    return index;
  }

  trackRow(index: number, value: number) {
    return value;
  }
}
