// src/front-end/angular/containers/app-angular.tsx
import {
  ChangeDetectorRef,
  Component,
  OnInit,
  OnDestroy,
} from '@angular/core';
import { NgRedux, select } from 'ng2-redux';
import { store } from '../../store/store';
import { Singletons } from '../singletons';
import { IState } from '../../reducers/root.reducer';
import {
  ActivePiece,
  Block,
  Board,
  InputDevice,
}  from '../components';
import { boardToArray } from '../../../util';
import { keyPress } from '../../actions/events.actions';
import { changeGameType } from '../../actions/game.actions';
import { Observable } from 'rxjs/Rx';
import { registerKeyControls } from '../../controls';
import {
  columnsFromBlock,
} from '../../../engine/block';


//     <ActivePiece p={ this.state.game.activePiece() } />


@Component({
  directives: [ActivePiece, Block, Board, InputDevice],
  selector: 'bd-angular',
  template: `
    <div class="bd-app">
      <h1>Block Drop</h1>
      <board [rowsCleared]="rowsCleared" [board]="board"></board> 
      <div class="bd-float">
        <select [ngModel]="(gameType$ | async)" 
        (change)="updateSelection($event.target.value)">
          <option *ngFor="let type of (gameTypes$ | async); let i = index" 
            [value]="i">
            {{ type }}
          </option> 
        </select>
        <div class="bd-float">
          <h2>Next:</h2>
          <block *ngFor="let p of preview" 
          [name]="p.name" 
          [cols]="p.cols"></block>
        </div>
        <div class="bd-debug bd-clear bd-float">
          <input-device [lastKeyCode]="(lastEvent$ | async).keyCode"> 
          </input-device> 
          <active-piece [centreX]="activePiece.centreX"
            [centreY]="activePiece.centreY"
            [desc]="stringify(activePiece.desc, null, 2)"
            [height]="activePiece.height"
            [name]="activePiece.name"
            [width]="activePiece.width"
            [x]="activePiece.x"
            [y]="activePiece.y"></active-piece>
        </div>
      </div>
    </div>
`,
})
export class App implements OnInit, OnDestroy {
  activePiece: any;
  board: any = [];
  deRegister: Function[] = [];
  @select((s) => s.game.gameType) gameType$: Observable<string>;
  @select((s) => s.game.gameTypes) gameTypes$: Observable<string[]>;
  @select((s) => s.game.lastEvent) lastEvent$: Observable<{ keyCode: number}>;
  preview: any[] = [];
  rowsCleared: number = 0;
  stringify = JSON.stringify.bind(JSON);
  constructor(private ngRedux: NgRedux<IState>,
              private singletons: Singletons,
              private cdRef: ChangeDetectorRef) {
    this.ngRedux.provideStore(store);
  }

  ngOnInit() {
    this.deRegister
      .push(this.singletons.engine.on('redraw', this.redraw.bind(this)));

    const { controls } = this.singletons.engine;

    this.deRegister.push(registerKeyControls({
      37: controls.moveLeft,
      38: controls.moveUp,
      39: controls.moveRight,
      40: controls.moveDown,
      81: controls.rotateLeft,
      87: controls.rotateRight,
    }, (evt) => this.ngRedux.dispatch(keyPress(evt))));

    this.redraw();
  }

  redraw() {
    // angular does *not* like getters do lots of mapping instead
    this.board = boardToArray(
      this.singletons.engine.buffer,
      this.singletons.engine.config.width);
    this.rowsCleared = this.singletons.engine.rowsCleared;
    this.preview = [];
    this.preview = this.singletons.engine.preview.map((el) => ({
      name: el.name,
      cols: columnsFromBlock(el),
    }));
    this.activePiece = this.singletons.engine.activePiece();
    this.cdRef.detectChanges();
  }

  ngOnDestroy() {
    this.deRegister.forEach((unsubscribe) => unsubscribe());
    this.deRegister = [];
  }

  updateSelection(selection) {
    this.ngRedux.dispatch(changeGameType(selection));
  }
}

// src/front-end/react/containers/app-react.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { keyPress } from '../../actions/events.actions';
import { changeGameType } from '../../actions/game.actions';
import { singletons } from '../../store/store';
import { registerKeyControls } from '../../controls';
import { boardToArray } from '../../../util';

import {
  ActivePiece,
  Block,
  Board, 
  InputDevice, 
} from '../components';

function mapStateToProps(state) {
  return {
    gameType: state.game.gameType,
    gameTypes: state.game.gameTypes,
    lastEvent: state.game.lastEvent,
  };
}

function mapDispatchToProps(dispatch)  {
  return {
    changeGameType: (type) => dispatch(changeGameType(type)),
    keyPress: (event) => dispatch(keyPress(event)),
  };
}

export const App = connect(
  mapStateToProps,
  mapDispatchToProps
)(React.createClass({
  deRegister: [],
  componentDidMount: function() {
    this.deRegister.push(this.state.game.on('redraw', () => {
      this.setState(() => ({
        board: boardToArray(singletons.engine.buffer,
          singletons.engine.config.width)
      }));
    }));

    const { controls } = this.state.game;

    this.deRegister.push(registerKeyControls({
      37: controls.moveLeft,
      38: controls.moveUp,
      39: controls.moveRight,
      40: controls.moveDown,
      81: controls.rotateLeft,
      87: controls.rotateRight,
    }, this.props.keyPress));
  },

  componentWillUnmount: function () {
    this.deRegister.forEach((unsubscribe) => unsubscribe());
    this.deRegister = [];
  },
  
  getInitialState: () => ({
    board: boardToArray(singletons.engine.buffer,
      singletons.engine.config.width),
    game: singletons.engine,
  }),

  render() {
    return (<div className='bd-app'>
      <h1>Block Drop</h1>
      <Board game= { this.state.game }
             board={ this.state.board } />
      <div className='bd-float'>
        <select name='game-type'
                value={ this.props.gameType }
                onChange={ this.gameType }>{
          this.props.gameTypes
            .map((opt, i) => <option key={i} value={i}>{
              opt
            }</option>)
        }</select>
        <div className='bd-float'>
          <h2>Next:</h2>
          { this.state.game.preview.map((block, i) => (
            <Block key={i} block={ block } />
          )) }
        </div>
        <div className='bd-debug bd-clear bd-float'>
          <InputDevice lastKeyCode={ this.props.lastEvent.keyCode } />
          <ActivePiece p={ this.state.game.activePiece() } />
        </div>
      </div>
    </div>);
  },
  gameType(event) {
    this.props.changeGameType(event.target.value);
  }
}));
